version: 0.1
phases:
  install:
    commands:
      - npm install -g serverless@1.3.0
  build:
    commands:
      - cd api && mvn clean install package -Drelease.version=prod && serverless deploy --stage=prod
